FROM joyqi/typecho:nightly-php8.0-fpm-alpine

RUN mkdir /usr/src/typecho/usr/{plugins,themes}
RUN touch /usr/src/typecho/usr/{plugins,themes}/.keep

ARG PGHOST
ARG PGPORT
ARG PGUSER
ARG PGPASSWORD
ARG PGDATABASE

ENV TYPECHO_DB_ADAPTER=Pdo_Pgsql
ENV TYPECHO_DB_HOST "$PGHOST"
ENV TYPECHO_DB_PORT "$PGPORT"
ENV TYPECHO_DB_USER "$PGUSER"
ENV TYPECHO_DB_PASSWORD "$PGPASSWORD"
ENV TYPECHO_DB_DATABASE "$PGDATABASE"
ENV TYPECHO_DB_NEXT=keep
ENV TYPECHO_INSTALL=1
ENV PORT=9000

EXPOSE 9000

RUN echo database host=$TYPECHO_DB_HOST port=$TYPECHO_DB_PORT user=$TYPECHO_DB_USER db=$TYPECHO_DB_DATABASE
